version: '3.3'

services:
  db:
    image: mysql:5.7 # to change to 8.4.0
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wordpress
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/html
    ports:
      - "8080:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: ${MYSQL_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: wordpress

  modsec-nginx:
    image: owasp/modsecurity-crs:3.3.5-nginx-alpine-202402140602
    depends_on:
      - wordpress
    environment:
      SERVERNAME: yourdomain.com
      BACKEND: http://wordpress:80
      PORT: "80"
      BLOCKING_PARANOIA: 1
      MODSEC_RESP_BODY_MIMETYPE: "text/plain text/html text/xml application/json"
      SSL_PORT: "443"
      SSL_CERT: "/etc/letsencrypt/live/nubitlan.com/fullchain.pem"
      SSL_CERT_KEY: "/etc/letsencrypt/live/nubitlan.com/privkey.pem"
      NGINX_ALWAYS_TLS_REDIRECT: "on"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./modsecurity_wordpress.conf:/etc/modsecurity.d/owasp-crs/custom-rules/modsecurity_wordpress.conf:ro
    restart: always

volumes:
    db_data: {}
    wordpress_data: {}
